# Generated by Django 5.1 on 2024-09-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
